(ns serdes_phy.actor
  "serdes_phy clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). High-speed SerDes PHY design.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; SerdesPhy
   {:db/ident :serdes_phy.SerdesPhy/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :serdes_phy.SerdesPhy/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.SerdesPhy/modulation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.SerdesPhy/dataRateGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.SerdesPhy/process :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.SerdesPhy/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.SerdesPhy/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Lane
   {:db/ident :serdes_phy.Lane/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :serdes_phy.Lane/phyId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Lane/index :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Lane/direction :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Lane/dataRateGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Lane/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Lane/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Equalizer
   {:db/ident :serdes_phy.Equalizer/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :serdes_phy.Equalizer/phyId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Equalizer/type :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Equalizer/taps :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Equalizer/gainDb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Equalizer/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Equalizer/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Pll
   {:db/ident :serdes_phy.Pll/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :serdes_phy.Pll/phyId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Pll/refClockMhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Pll/jitterPs :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Pll/lockTimeUs :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Pll/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.Pll/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; EyeDiagram
   {:db/ident :serdes_phy.EyeDiagram/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :serdes_phy.EyeDiagram/laneId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.EyeDiagram/eyeHeightMv :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.EyeDiagram/eyeWidthPs :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.EyeDiagram/ber :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.EyeDiagram/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.EyeDiagram/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; BertRun
   {:db/ident :serdes_phy.BertRun/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :serdes_phy.BertRun/phyId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.BertRun/patternType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.BertRun/bitsTested :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.BertRun/errors :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.BertRun/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :serdes_phy.BertRun/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"SerdesPhy" "Lane" "Equalizer" "Pll" "EyeDiagram" "BertRun"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "serdes_phy: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "serdes_phy: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "serdes_phy: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── SerdesPhy ────────────────────────────────────────────────────────────────
(defn create-serdes-phy
  "Create a SerdesPhy."
  [port data]
  (require-fields data ["name" "modulation"])
  (let [id (new-id "ser_ser")
        e {:db/id id
           :serdes_phy.SerdesPhy/id id
           :serdes_phy.SerdesPhy/name (get data :name)
           :serdes_phy.SerdesPhy/modulation (get data :modulation)
           :serdes_phy.SerdesPhy/dataRateGbps (as-double (get data :dataRateGbps))
           :serdes_phy.SerdesPhy/process (get data :process)
           :serdes_phy.SerdesPhy/createdAt (now)
           :serdes_phy.SerdesPhy/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-serdes-phies
  "List SerdesPhy with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-serdes-phies port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :serdes_phy.SerdesPhy/id))
         rows (apply-filters rows (:filter opts) [:serdes_phy.SerdesPhy/name :serdes_phy.SerdesPhy/modulation :serdes_phy.SerdesPhy/dataRateGbps :serdes_phy.SerdesPhy/process])]
     (paginate rows opts))))

(defn get-serdes-phy
  "Retrieve a SerdesPhy by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-serdes-phy port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-serdes-phy
  "Update a SerdesPhy; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :serdes_phy.SerdesPhy/name (get data :name)]))
                   (cond-> (contains? data :modulation) (conj [:db/add id :serdes_phy.SerdesPhy/modulation (get data :modulation)]))
                   (cond-> (contains? data :dataRateGbps) (conj [:db/add id :serdes_phy.SerdesPhy/dataRateGbps (as-double (get data :dataRateGbps))]))
                   (cond-> (contains? data :process) (conj [:db/add id :serdes_phy.SerdesPhy/process (get data :process)]))
                   (conj [:db/add id :serdes_phy.SerdesPhy/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-serdes-phy
  "Delete a SerdesPhy."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Lane ────────────────────────────────────────────────────────────────
(defn create-lane
  "Create a Lane."
  [port data]
  (require-fields data ["index" "direction"])
  (let [id (new-id "ser_lan")
        e {:db/id id
           :serdes_phy.Lane/id id
           :serdes_phy.Lane/phyId (get data :phyId)
           :serdes_phy.Lane/index (as-long (get data :index))
           :serdes_phy.Lane/direction (get data :direction)
           :serdes_phy.Lane/dataRateGbps (as-double (get data :dataRateGbps))
           :serdes_phy.Lane/createdAt (now)
           :serdes_phy.Lane/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-lanes
  "List Lane with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-lanes port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :serdes_phy.Lane/id))
         rows (apply-filters rows (:filter opts) [:serdes_phy.Lane/phyId :serdes_phy.Lane/index :serdes_phy.Lane/direction :serdes_phy.Lane/dataRateGbps])]
     (paginate rows opts))))

(defn get-lane
  "Retrieve a Lane by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-lane port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-lane
  "Update a Lane; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :phyId) (conj [:db/add id :serdes_phy.Lane/phyId (get data :phyId)]))
                   (cond-> (contains? data :index) (conj [:db/add id :serdes_phy.Lane/index (as-long (get data :index))]))
                   (cond-> (contains? data :direction) (conj [:db/add id :serdes_phy.Lane/direction (get data :direction)]))
                   (cond-> (contains? data :dataRateGbps) (conj [:db/add id :serdes_phy.Lane/dataRateGbps (as-double (get data :dataRateGbps))]))
                   (conj [:db/add id :serdes_phy.Lane/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-lane
  "Delete a Lane."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Equalizer ────────────────────────────────────────────────────────────────
(defn create-equalizer
  "Create a Equalizer."
  [port data]
  (require-fields data ["type" "taps"])
  (let [id (new-id "ser_equ")
        e {:db/id id
           :serdes_phy.Equalizer/id id
           :serdes_phy.Equalizer/phyId (get data :phyId)
           :serdes_phy.Equalizer/type (get data :type)
           :serdes_phy.Equalizer/taps (as-long (get data :taps))
           :serdes_phy.Equalizer/gainDb (as-double (get data :gainDb))
           :serdes_phy.Equalizer/createdAt (now)
           :serdes_phy.Equalizer/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-equalizers
  "List Equalizer with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-equalizers port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :serdes_phy.Equalizer/id))
         rows (apply-filters rows (:filter opts) [:serdes_phy.Equalizer/phyId :serdes_phy.Equalizer/type :serdes_phy.Equalizer/taps :serdes_phy.Equalizer/gainDb])]
     (paginate rows opts))))

(defn get-equalizer
  "Retrieve a Equalizer by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-equalizer port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-equalizer
  "Update a Equalizer; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :phyId) (conj [:db/add id :serdes_phy.Equalizer/phyId (get data :phyId)]))
                   (cond-> (contains? data :type) (conj [:db/add id :serdes_phy.Equalizer/type (get data :type)]))
                   (cond-> (contains? data :taps) (conj [:db/add id :serdes_phy.Equalizer/taps (as-long (get data :taps))]))
                   (cond-> (contains? data :gainDb) (conj [:db/add id :serdes_phy.Equalizer/gainDb (as-double (get data :gainDb))]))
                   (conj [:db/add id :serdes_phy.Equalizer/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-equalizer
  "Delete a Equalizer."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Pll ────────────────────────────────────────────────────────────────
(defn create-pll
  "Create a Pll."
  [port data]
  (require-fields data ["refClockMhz" "jitterPs"])
  (let [id (new-id "ser_pll")
        e {:db/id id
           :serdes_phy.Pll/id id
           :serdes_phy.Pll/phyId (get data :phyId)
           :serdes_phy.Pll/refClockMhz (as-double (get data :refClockMhz))
           :serdes_phy.Pll/jitterPs (as-double (get data :jitterPs))
           :serdes_phy.Pll/lockTimeUs (as-double (get data :lockTimeUs))
           :serdes_phy.Pll/createdAt (now)
           :serdes_phy.Pll/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-plls
  "List Pll with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-plls port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :serdes_phy.Pll/id))
         rows (apply-filters rows (:filter opts) [:serdes_phy.Pll/phyId :serdes_phy.Pll/refClockMhz :serdes_phy.Pll/jitterPs :serdes_phy.Pll/lockTimeUs])]
     (paginate rows opts))))

(defn get-pll
  "Retrieve a Pll by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-pll port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-pll
  "Update a Pll; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :phyId) (conj [:db/add id :serdes_phy.Pll/phyId (get data :phyId)]))
                   (cond-> (contains? data :refClockMhz) (conj [:db/add id :serdes_phy.Pll/refClockMhz (as-double (get data :refClockMhz))]))
                   (cond-> (contains? data :jitterPs) (conj [:db/add id :serdes_phy.Pll/jitterPs (as-double (get data :jitterPs))]))
                   (cond-> (contains? data :lockTimeUs) (conj [:db/add id :serdes_phy.Pll/lockTimeUs (as-double (get data :lockTimeUs))]))
                   (conj [:db/add id :serdes_phy.Pll/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-pll
  "Delete a Pll."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── EyeDiagram ────────────────────────────────────────────────────────────────
(defn create-eye-diagram
  "Create a EyeDiagram."
  [port data]
  (require-fields data ["eyeHeightMv" "eyeWidthPs"])
  (let [id (new-id "ser_eye")
        e {:db/id id
           :serdes_phy.EyeDiagram/id id
           :serdes_phy.EyeDiagram/laneId (get data :laneId)
           :serdes_phy.EyeDiagram/eyeHeightMv (as-double (get data :eyeHeightMv))
           :serdes_phy.EyeDiagram/eyeWidthPs (as-double (get data :eyeWidthPs))
           :serdes_phy.EyeDiagram/ber (as-double (get data :ber))
           :serdes_phy.EyeDiagram/createdAt (now)
           :serdes_phy.EyeDiagram/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-eye-diagrams
  "List EyeDiagram with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-eye-diagrams port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :serdes_phy.EyeDiagram/id))
         rows (apply-filters rows (:filter opts) [:serdes_phy.EyeDiagram/laneId :serdes_phy.EyeDiagram/eyeHeightMv :serdes_phy.EyeDiagram/eyeWidthPs :serdes_phy.EyeDiagram/ber])]
     (paginate rows opts))))

(defn get-eye-diagram
  "Retrieve a EyeDiagram by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-eye-diagram port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :laneId) (get rec :serdes_phy.EyeDiagram/laneId))
         (assoc :laneId-obj (-pull port (get rec :serdes_phy.EyeDiagram/laneId))))))))

(defn update-eye-diagram
  "Update a EyeDiagram; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :laneId) (conj [:db/add id :serdes_phy.EyeDiagram/laneId (get data :laneId)]))
                   (cond-> (contains? data :eyeHeightMv) (conj [:db/add id :serdes_phy.EyeDiagram/eyeHeightMv (as-double (get data :eyeHeightMv))]))
                   (cond-> (contains? data :eyeWidthPs) (conj [:db/add id :serdes_phy.EyeDiagram/eyeWidthPs (as-double (get data :eyeWidthPs))]))
                   (cond-> (contains? data :ber) (conj [:db/add id :serdes_phy.EyeDiagram/ber (as-double (get data :ber))]))
                   (conj [:db/add id :serdes_phy.EyeDiagram/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-eye-diagram
  "Delete a EyeDiagram."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── BertRun ────────────────────────────────────────────────────────────────
(defn create-bert-run
  "Create a BertRun."
  [port data]
  (require-fields data ["patternType" "bitsTested"])
  (let [id (new-id "ser_ber")
        e {:db/id id
           :serdes_phy.BertRun/id id
           :serdes_phy.BertRun/phyId (get data :phyId)
           :serdes_phy.BertRun/patternType (get data :patternType)
           :serdes_phy.BertRun/bitsTested (as-long (get data :bitsTested))
           :serdes_phy.BertRun/errors (as-long (get data :errors))
           :serdes_phy.BertRun/createdAt (now)
           :serdes_phy.BertRun/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-bert-runs
  "List BertRun with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-bert-runs port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :serdes_phy.BertRun/id))
         rows (apply-filters rows (:filter opts) [:serdes_phy.BertRun/phyId :serdes_phy.BertRun/patternType :serdes_phy.BertRun/bitsTested :serdes_phy.BertRun/errors])]
     (paginate rows opts))))

(defn get-bert-run
  "Retrieve a BertRun by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-bert-run port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-bert-run
  "Update a BertRun; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :phyId) (conj [:db/add id :serdes_phy.BertRun/phyId (get data :phyId)]))
                   (cond-> (contains? data :patternType) (conj [:db/add id :serdes_phy.BertRun/patternType (get data :patternType)]))
                   (cond-> (contains? data :bitsTested) (conj [:db/add id :serdes_phy.BertRun/bitsTested (as-long (get data :bitsTested))]))
                   (cond-> (contains? data :errors) (conj [:db/add id :serdes_phy.BertRun/errors (as-long (get data :errors))]))
                   (conj [:db/add id :serdes_phy.BertRun/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-bert-run
  "Delete a BertRun."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/serdesphies" :op :create :entity "SerdesPhy"}
   {:method "GET" :path "/v1/serdesphies" :op :list :entity "SerdesPhy"}
   {:method "GET" :path "/v1/serdesphies/:id" :op :get :entity "SerdesPhy"}
   {:method "PATCH" :path "/v1/serdesphies/:id" :op :update :entity "SerdesPhy"}
   {:method "DELETE" :path "/v1/serdesphies/:id" :op :delete :entity "SerdesPhy"}
   {:method "POST" :path "/v1/lanes" :op :create :entity "Lane"}
   {:method "GET" :path "/v1/lanes" :op :list :entity "Lane"}
   {:method "GET" :path "/v1/lanes/:id" :op :get :entity "Lane"}
   {:method "PATCH" :path "/v1/lanes/:id" :op :update :entity "Lane"}
   {:method "DELETE" :path "/v1/lanes/:id" :op :delete :entity "Lane"}
   {:method "POST" :path "/v1/equalizers" :op :create :entity "Equalizer"}
   {:method "GET" :path "/v1/equalizers" :op :list :entity "Equalizer"}
   {:method "GET" :path "/v1/equalizers/:id" :op :get :entity "Equalizer"}
   {:method "PATCH" :path "/v1/equalizers/:id" :op :update :entity "Equalizer"}
   {:method "DELETE" :path "/v1/equalizers/:id" :op :delete :entity "Equalizer"}
   {:method "POST" :path "/v1/plls" :op :create :entity "Pll"}
   {:method "GET" :path "/v1/plls" :op :list :entity "Pll"}
   {:method "GET" :path "/v1/plls/:id" :op :get :entity "Pll"}
   {:method "PATCH" :path "/v1/plls/:id" :op :update :entity "Pll"}
   {:method "DELETE" :path "/v1/plls/:id" :op :delete :entity "Pll"}
   {:method "POST" :path "/v1/eyediagrams" :op :create :entity "EyeDiagram"}
   {:method "GET" :path "/v1/eyediagrams" :op :list :entity "EyeDiagram"}
   {:method "GET" :path "/v1/eyediagrams/:id" :op :get :entity "EyeDiagram"}
   {:method "PATCH" :path "/v1/eyediagrams/:id" :op :update :entity "EyeDiagram"}
   {:method "DELETE" :path "/v1/eyediagrams/:id" :op :delete :entity "EyeDiagram"}
   {:method "POST" :path "/v1/bertruns" :op :create :entity "BertRun"}
   {:method "GET" :path "/v1/bertruns" :op :list :entity "BertRun"}
   {:method "GET" :path "/v1/bertruns/:id" :op :get :entity "BertRun"}
   {:method "PATCH" :path "/v1/bertruns/:id" :op :update :entity "BertRun"}
   {:method "DELETE" :path "/v1/bertruns/:id" :op :delete :entity "BertRun"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"serdesphies" {:create create-serdes-phy :list list-serdes-phies :get get-serdes-phy :update update-serdes-phy :delete delete-serdes-phy}
   "lanes" {:create create-lane :list list-lanes :get get-lane :update update-lane :delete delete-lane}
   "equalizers" {:create create-equalizer :list list-equalizers :get get-equalizer :update update-equalizer :delete delete-equalizer}
   "plls" {:create create-pll :list list-plls :get get-pll :update update-pll :delete delete-pll}
   "eyediagrams" {:create create-eye-diagram :list list-eye-diagrams :get get-eye-diagram :update update-eye-diagram :delete delete-eye-diagram}
   "bertruns" {:create create-bert-run :list list-bert-runs :get get-bert-run :update update-bert-run :delete delete-bert-run}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "serdes_phy-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
